-- Migration: Add shipping API enhancements (cache and logs)
-- 20260708100000_add_shipping_api_enhancements.sql

BEGIN;

-- 1. Create shipping_quotes_cache table
CREATE TABLE IF NOT EXISTS public.shipping_quotes_cache (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    origin_cep text NOT NULL,
    destination_cep text NOT NULL,
    cart_hash text NOT NULL,
    options jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone(
        'utc'::text, now()
    ) NOT NULL
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_shipping_quotes_cache_lookup
ON public.shipping_quotes_cache (origin_cep, destination_cep, cart_hash);

-- Enable RLS (Service role will bypass RLS, other roles have no access by default)
ALTER TABLE public.shipping_quotes_cache ENABLE ROW LEVEL SECURITY;

-- 2. Create shipping_calculation_logs table
CREATE TABLE IF NOT EXISTS public.shipping_calculation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_cep text NOT NULL,
    destination_cep text NOT NULL,
    provider text NOT NULL,
    cart_items jsonb NOT NULL,
    response_time_ms integer NOT NULL,
    status text NOT NULL, -- 'success', 'contingency', 'error'
    error_message text,
    created_at timestamp with time zone DEFAULT timezone(
        'utc'::text, now()
    ) NOT NULL
);

-- Index for admin logs query speed
CREATE INDEX IF NOT EXISTS idx_shipping_calculation_logs_created_at
ON public.shipping_calculation_logs (created_at DESC);

-- Enable RLS
ALTER TABLE public.shipping_calculation_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for Admin access
CREATE POLICY "Admins have full access to shipping calculation logs"
ON public.shipping_calculation_logs
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

COMMIT;
