-- ============================================================================
-- ROLLBACK MANUAL da 20261184000000 — o PIX do balcão abre na hora
-- ============================================================================
-- OBSOLETO: NÃO EXECUTAR ESTE ARQUIVO. Ele não atualiza o ledger nem recusa
-- pedidos criados. Use exclusivamente scripts/sql/pix-84-85-revert.sql pelo
-- workflow rollback-pix-84-85.yml; a verificação deve aprovar o estado.
--
-- O QUE ESTE ARQUIVO DESFAZ: os gatilhos `tr_venda_do_balcao_paga_e_entregue`
-- e `tr_venda_do_balcao_guarda_o_status`, as funções deles e
-- `public.iniciar_venda_presencial_pix`. As três funções são NOVAS — não
-- substituíram corpo nenhum —, então desfazer é derrubar.
--
-- O QUE ELE NÃO TOCA, DE PROPÓSITO:
--   - `registrar_venda_presencial`, `confirmar_pagamento`,
--     `expirar_pedidos_vencidos` e as funções `fin_*`: a ida não encostou
--     nelas.
--   - OS PEDIDOS JÁ CRIADOS. Um PIX do balcão é um pedido 'online' comum
--     (canal presencial): se estiver 'aguardando', a expiração devolve o
--     estoque e o webhook confirma o pagamento como sempre — só que, sem o
--     gatilho, um PIX pago depois do rollback fica 'pending' e precisa ser
--     marcado como entregue à mão no painel (Pedidos → Entregue). Nenhum dado
--     é lido, escrito ou apagado aqui.
--
-- EFEITO COLATERAL ESPERADO: a tela Vender, se já estiver no ar, recebe
-- 42883/PGRST202 ao tocar "Gerar PIX" e mostra que o PIX com QR não está
-- liberado; dinheiro, PIX na chave e maquininha seguem funcionando.
--
-- IDEMPOTÊNCIA: `DROP ... IF EXISTS` — rodar duas vezes dá o mesmo estado.
-- Assinatura completa no DROP FUNCTION (evita derrubar sobrecarga errada).
--
-- ESTE ARQUIVO FOI DESATIVADO. O workflow antigo não aceita rollback.
--
-- VERIFICAÇÃO pós-rollback:
--   SELECT count(*) FROM pg_trigger WHERE tgname IN ('tr_venda_do_balcao_paga_e_entregue', 'tr_venda_do_balcao_guarda_o_status');
--   -- esperado: 0.
--   SELECT count(*) FROM pg_proc WHERE proname IN ('iniciar_venda_presencial_pix', 'venda_do_balcao_paga_e_entregue', 'venda_do_balcao_guarda_o_status');
--   -- esperado: 0.
-- ============================================================================

DO $$ BEGIN
  RAISE EXCEPTION 'Rollback manual obsoleto; use scripts/sql/pix-84-85-revert.sql';
END $$;
